#!/bin/bash

set -eo pipefail

date="$(date '+%Y-%m-%d')"

sketch="$date"

num=1
while test -f "$sketch.html"; do
  ((num=num+1))
  sketch="$date-0$num"
done

echo "creating $sketch"
cp template.html "$sketch.html"

echo "<li><a href=\"$sketch.html\">$sketch</a></li>" >> index.html